apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-argocd"
      labels:
        freewheel.tv/app: argocd
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: north-south
      source:
        repoURL: "{{ metadata.annotations.scm-home }}"
        targetRevision: HEAD
        path: argocd/argocd
      destination:
        server: "{{server}}"
        namespace: argocd
      syncPolicy:
        # automated:
        #   prune: true
        syncOptions:
          - PruneLast=true
